# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-08 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status_options',
            field=models.CharField(blank=True, choices=[('D', 'Done'), ('L', 'Looking'), ('W', 'Working')], max_length=1, null=True),
        ),
    ]
