# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-11 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_status_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='posts.Post'),
            preserve_default=False,
        ),
    ]
