# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-11 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_status_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='posts.Post'),
        ),
    ]
